application: example
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default


handlers:
- url: (.*)/
  static_files: output/index.html
  upload: output/index.html

- url: /
  static_dir: output

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?content